services:
  saleor-db:
    image: postgres:15-alpine
    container_name: saleor-db
    environment:
      POSTGRES_DB: saleor
      POSTGRES_USER: saleor
      POSTGRES_PASSWORD: saleor_pass
    volumes:
      - saleor-db:/var/lib/postgresql/data
    restart: unless-stopped

  saleor:
    image: ghcr.io/saleor/saleor:latest
    container_name: saleor
    depends_on:
      - saleor-db
    ports:
      - "8522:8000"
    environment:
      DATABASE_URL: postgres://saleor:saleor_pass@saleor-db:5432/saleor
      SECRET_KEY: change_me
    restart: unless-stopped

volumes:
  saleor-db:

