services:
  postiz-db:
    image: postgres:16-alpine
    container_name: postiz-db
    environment:
      POSTGRES_DB: postiz
      POSTGRES_USER: postiz
      POSTGRES_PASSWORD: postiz_pass
    volumes:
      - postiz-db:/var/lib/postgresql/data
    restart: unless-stopped

  postiz-redis:
    image: redis:alpine
    container_name: postiz-redis
    restart: unless-stopped

  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    container_name: postiz
    ports:
      - "8626:3000"
    depends_on:
      - postiz-db
      - postiz-redis
    environment:
      - DATABASE_URL=postgresql://postiz:postiz_pass@postiz-db:5432/postiz
      - REDIS_URL=redis://postiz-redis:6379
      - JWT_SECRET=your_jwt_secret_here_change_this
      - NEXTAUTH_SECRET=your_nextauth_secret_here_change_this
      - NEXTAUTH_URL=http://localhost:8626
      - FRONTEND_URL=http://localhost:8626
      - NODE_ENV=production
      - UPLOAD_DIRECTORY=/tmp/uploads
    volumes:
      - postiz-uploads:/tmp/uploads
    restart: unless-stopped

volumes:
  postiz-db:
  postiz-uploads: