services:
  huginn-db:
    image: mysql:8.0
    container_name: huginn-db
    environment:
      - MYSQL_ROOT_PASSWORD=huginn_root
      - MYSQL_DATABASE=huginn
      - MYSQL_USER=huginn
      - MYSQL_PASSWORD=huginn_pass
    volumes:
      - huginn-db:/var/lib/mysql
    restart: always

  huginn:
    image: ghcr.io/huginn/huginn-single-process:latest
    container_name: huginn
    ports:
      - "8403:3000"
    depends_on:
      - huginn-db
    environment:
      - DATABASE_ADAPTER=mysql2
      - DATABASE_HOST=huginn-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=huginn
      - DATABASE_USERNAME=huginn
      - DATABASE_PASSWORD=huginn_pass
      - APP_SECRET_TOKEN=change_this_secret_token_to_something_random
      - DOMAIN=localhost:8403
      - SMTP_DOMAIN=localhost
      - SMTP_USER_NAME=huginn@localhost
      - SMTP_PASSWORD=password
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - EMAIL_FROM_ADDRESS=huginn@localhost
      - RAILS_ENV=production
    restart: always

volumes:
  huginn-db: