services:
  database:
    image: mysql:8.0
    container_name: mautic-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mauticdbroot
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: mauticdbpass
    volumes:
      - database_data:/var/lib/mysql
    restart: always

  mautic:
    image: mautic/mautic:v5.2.0
    container_name: mautic
    depends_on:
      - database
    ports:
      - "8307:80"
    environment:
      MAUTIC_DB_HOST: database
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: mauticdbpass
      MAUTIC_DB_NAME: mautic
      MAUTIC_RUN_CRON_JOBS: 'true'
      MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0
    volumes:
      - mautic_data:/var/www/html
    restart: always

volumes:
  database_data:
  mautic_data:
