services:
  umami-db:
    image: postgres:16-alpine
    container_name: umami-db
    environment:
      - POSTGRES_DB=umami
      - POSTGRES_USER=umami
      - POSTGRES_PASSWORD=umami_pass
    volumes:
      - umami-db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    ports:
      - "8520:3000"
    depends_on:
      umami-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://umami:umami_pass@umami-db:5432/umami
      - DATABASE_TYPE=postgresql
      - APP_SECRET=change_this_secret_to_something_random
      - HOSTNAME=0.0.0.0
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  umami-db: