services:
  nextcloud-db:
    image: postgres:16-alpine
    container_name: nextcloud-db
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud_pass
    volumes:
      - nextcloud-db:/var/lib/postgresql/data
    restart: always

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - "8518:80"
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud_pass
      - REDIS_HOST=nextcloud-redis
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin123
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost
    volumes:
      - nextcloud-data:/var/www/html
    restart: always

volumes:
  nextcloud-db:
  nextcloud-data: