services:
  discourse-db:
    image: postgres:16-alpine
    container_name: discourse-db
    environment:
      POSTGRES_DB: discourse
      POSTGRES_USER: discourse
      POSTGRES_PASSWORD: discourse_pass
    volumes:
      - discourse-db:/var/lib/postgresql/data
    restart: unless-stopped

  discourse-redis:
    image: redis:alpine
    container_name: discourse-redis
    restart: unless-stopped

  discourse:
    image: discourse/discourse:stable-release
    container_name: discourse
    ports:
      - "8610:80"
    depends_on:
      - discourse-db
      - discourse-redis
    environment:
      DISCOURSE_HOSTNAME: localhost:8610
      DISCOURSE_DATABASE_HOST: discourse-db
      DISCOURSE_DATABASE_PORT: 5432
      DISCOURSE_DATABASE_NAME: discourse
      DISCOURSE_DATABASE_USERNAME: discourse
      DISCOURSE_DATABASE_PASSWORD: discourse_pass
      DISCOURSE_REDIS_HOST: discourse-redis
      DISCOURSE_REDIS_PORT: 6379
      DISCOURSE_DEVELOPER_EMAILS: admin@discourse.local
      DISCOURSE_SMTP_ADDRESS: 
      DISCOURSE_SMTP_PORT: 587
      DISCOURSE_SMTP_USER_NAME: 
      DISCOURSE_SMTP_PASSWORD: 
      DISCOURSE_SMTP_ENABLE_START_TLS: true
    volumes:
      - discourse-data:/shared
    restart: unless-stopped

volumes:
  discourse-db:
  discourse-data: