services:
  wordpress-db:
    image: mariadb:10.6.4-focal
    container_name: wordpress-db
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress_root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress_pass
    volumes:
      - wordpress-db:/var/lib/mysql
    restart: always
    expose:
      - 3306
      - 33060

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8500:80"
    depends_on:
      - wordpress-db
    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress_pass
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress-data:/var/www/html
    restart: always

volumes:
  wordpress-db:
  wordpress-data: