services:
  temporal-db:
    image: postgres:16-alpine
    container_name: temporal-db
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
      POSTGRES_DB: temporal
    volumes:
      - temporal-db:/var/lib/postgresql/data
    restart: unless-stopped

  temporal-setup:
    image: temporalio/auto-setup:latest
    container_name: temporal-setup
    depends_on:
      - temporal-db
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-db
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    volumes:
      - temporal-config:/etc/temporal/config/dynamicconfig
    restart: "no"

  temporal:
    image: temporalio/server:latest
    container_name: temporal
    depends_on:
      - temporal-db
      - temporal-setup
    ports:
      - "8620:7233"   # gRPC endpoint
      - "8621:7234"   # gRPC endpoint for worker service
      - "8622:7235"   # HTTP API endpoint  
      - "8623:7239"   # Health check endpoint
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-db
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=false
      - ES_SEEDS=
      - ES_VERSION=v7
    volumes:
      - temporal-config:/etc/temporal/config/dynamicconfig
    restart: unless-stopped

  temporal-web:
    image: temporalio/web:latest
    container_name: temporal-web
    depends_on:
      - temporal
    ports:
      - "8624:8080"
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    restart: unless-stopped

  temporal-admin-tools:
    image: temporalio/admin-tools:latest
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    stdin_open: true
    tty: true
    restart: "no"

volumes:
  temporal-db:
  temporal-config: