services:
  drupal:
    image: drupal:latest
    container_name: drupal
    ports:
      - "8521:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    restart: unless-stopped
    depends_on:
      - drupal-db

  drupal-db:
    image: mysql:8.0
    container_name: drupal-db
    environment:
      MYSQL_ROOT_PASSWORD: drupal_root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal_pass
    volumes:
      - drupal-db:/var/lib/mysql
    restart: unless-stopped

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-db:

