services:
  ghost-db:
    image: mariadb:10.11
    container_name: ghost-db
    environment:
      - MYSQL_ROOT_PASSWORD=ghost_root
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=ghost_pass
    volumes:
      - ghost-db:/var/lib/mysql
    restart: always

  ghost:
    image: ghost:latest
    container_name: ghost
    ports:
      - "8501:2368"
    depends_on:
      - ghost-db
    environment:
      - NODE_ENV=production
      - url=http://localhost:8501
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__port=3306
      - database__connection__user=ghost
      - database__connection__password=ghost_pass
      - database__connection__database=ghost
    volumes:
      - ghost-content:/var/lib/ghost/content
    restart: always

volumes:
  ghost-db:
  ghost-content: