services:
  db:
    image: postgres:15-alpine
    container_name: listmonk-db
    environment:
      POSTGRES_USER: listmonk
      POSTGRES_PASSWORD: listmonk
      POSTGRES_DB: listmonk
    volumes:
      - listmonk_data:/var/lib/postgresql/data
    restart: unless-stopped

  listmonk:
    image: listmonk/listmonk:latest
    container_name: listmonk
    depends_on:
      - db
    ports:
      - "8301:9000"
    environment:
      LISTMONK_app__address: 0.0.0.0:9000
      LISTMONK_db__host: db
      LISTMONK_db__user: listmonk
      LISTMONK_db__password: listmonk
      LISTMONK_db__database: listmonk
      LISTMONK_db__ssl_mode: disable
    restart: unless-stopped
    command: [sh, -c, "listmonk --install --yes && listmonk"]

volumes:
  listmonk_data:
