services:
  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8523:8088"
    environment:
      SUPERSET_SECRET_KEY: change_me_super_secret
      ADMIN_USERNAME: admin
      ADMIN_FIRST_NAME: Admin
      ADMIN_LAST_NAME: User
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - superset-db
    restart: unless-stopped

  superset-db:
    image: postgres:15-alpine
    container_name: superset-db
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset_pass
    volumes:
      - superset-db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  superset_home:
  superset-db:

