services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8516:9000"   # HTTP
      - "8517:9443"   # HTTPS
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock

volumes:
  portainer-data: